### ISSUE TITLE
error

### ISSUE THREAD

**Issue by yangfangyuan0102** [HaploKit/vechat#10]
vechat gm.ont.fastq.gz --platform ont --split -t 24 -o gm.ont.cor.fa

Performing the 1 iteration for error correction...
processing chunk 1...

#after a while......

Traceback (most recent call last):
  File "/home/yfy/miniconda3/envs/assembly/bin/vechat", line 303, in <module>
    run_error_correction(
  File "/home/yfy/miniconda3/envs/assembly/bin/vechat", line 48, in run_error_correction
    sub_query_sequences = extract_sub_sequences(sequences,overlap,chunk_target_sequence)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yfy/miniconda3/envs/assembly/bin/vechat", line 76, in extract_sub_sequences
    mode=fq_or_fa(chunk_target_sequence)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yfy/miniconda3/envs/assembly/bin/vechat", line 152, in fq_or_fa
    s = fr.readline()[0]
        ^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte

**Comment by unavailable-2374** [comment]
> vechat gm.ont.fastq.gz --platform ont --split -t 24 -o gm.ont.cor.fa
> 
> Performing the 1 iteration for error correction... processing chunk 1...
> 
> #after a while......
> 
> Traceback (most recent call last): File "/home/yfy/miniconda3/envs/assembly/bin/vechat", line 303, in run_error_correction( File "/home/yfy/miniconda3/envs/assembly/bin/vechat", line 48, in run_error_correction sub_query_sequences = extract_sub_sequences(sequences,overlap,chunk_target_sequence) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/home/yfy/miniconda3/envs/assembly/bin/vechat", line 76, in extract_sub_sequences mode=fq_or_fa(chunk_target_sequence) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/home/yfy/miniconda3/envs/assembly/bin/vechat", line 152, in fq_or_fa s = fr.readline()[0] ^^^^^^^^^^^^^ File "", line 322, in decode UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte

Hello Yuan

I got the same problem, have you solved it ?

thanks！
