### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by yzhang-github-pub** [HaploKit/vechat#7]
First I tried to install using conda as 'conda install -c bioconda vechat'. conda complained vechat not found.

Then I tried to install from source. With this: 'python ./scripts/vechat -h', I got:

**gmake: Makefile: No such file or directory
gmake: *** No rule to make target `Makefile'.  Stop.**

Any help is greatly appreciated.

**Comment by HaploKit** [comment]
Sorry for the delay, it is available to install VeChat  via ‘conda’ now, see commands below:

conda create -n vechat
conda activate vechat
conda install -c bioconda vechat
